const KEY='state_entries_v1'; const metrics=[['calm','Calmness'],['restless','Restlessness'],['anxiety','Anxiety'],['impulsive','Impulsivity'],['focus','Focus'],['motivation','Motivation'],['urges','Sexual urges']];
let entries=JSON.parse(localStorage.getItem(KEY)||'[]'); let current={date:new Date().toISOString().slice(0,10),gym:false,bhang:false,fap:false,sleep:5,study:0,note:''}; 
const form=document.getElementById('form');
function renderForm(){form.innerHTML=metrics.map(([k,n])=>`<label class="metric"><span>${n}<b id="v-${k}">${current[k]??5}</b></span><input data-k="${k}" type="range" min="0" max="10" value="${current[k]??5}"></label>`).join('')+`<p><b>Habits & context</b></p><div class="row">${[['gym','Gym today?'],['bhang','Bhang/cannabis?'],['fap','Masturbation/porn?']].map(([k,n])=>`<button class="pill ${current[k]?'active':''}" data-toggle="${k}">${n}: ${current[k]?'Yes':'No'}</button>`).join('')}</div><label class="metric"><span>Sleep quality <b id="v-sleep">${current.sleep}</b></span><input id="sleep" type="range" min="0" max="10" value="${current.sleep}"></label><label>Study time (minutes)<input id="study" type="number" min="0" value="${current.study}"></label><label>Anything unusual today?<textarea id="note" placeholder="e.g. After gym I felt unusually calm.">${current.note}</textarea>`; 
form.querySelectorAll('input[type=range][data-k]').forEach(x=>x.oninput=()=>{current[x.dataset.k]=+x.value;document.getElementById('v-'+x.dataset.k).textContent=x.value});document.getElementById('sleep').oninput=e=>{current.sleep=+e.target.value;document.getElementById('v-sleep').textContent=e.target.value};document.getElementById('study').oninput=e=>current.study=+e.target.value;document.getElementById('note').oninput=e=>current.note=e.target.value;form.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{current[b.dataset.toggle]=!current[b.dataset.toggle];renderForm()})}
function save(){current.date=new Date().toISOString().slice(0,10); entries=entries.filter(e=>e.date!==current.date);entries.push({...current});entries.sort((a,b)=>b.date.localeCompare(a.date));localStorage.setItem(KEY,JSON.stringify(entries));document.getElementById('saved').textContent='Saved ✓';render();setTimeout(()=>document.getElementById('saved').textContent='',1500)}
function avg(a,k){let x=a.map(e=>+e[k]).filter(Number.isFinite);return x.length?x.reduce((s,v)=>s+v,0)/x.length:null}
function insights(){let el=document.getElementById('insights');if(entries.length<2){el.innerHTML='<p class="empty">Add a few days first. Insights appear automatically.</p>';return}let gym=entries.filter(e=>e.gym),nog=entries.filter(e=>!e.gym), nb=entries.filter(e=>!e.bhang), b=entries.filter(e=>e.bhang);let out=[]; if(gym.length&&nog.length)out.push(`On gym days, calmness averages <b>${avg(gym,'calm').toFixed(1)}</b> vs <b>${avg(nog,'calm').toFixed(1)}</b> on non-gym days.`);if(nb.length&&b.length)out.push(`On cannabis-free days, anxiety averages <b>${avg(nb,'anxiety').toFixed(1)}</b> vs <b>${avg(b,'anxiety').toFixed(1)}</b> on cannabis-use days.`);out.push(`Across all entries: focus <b>${avg(entries,'focus').toFixed(1)}</b>, restlessness <b>${avg(entries,'restless').toFixed(1)}</b>, study <b>${Math.round(avg(entries,'study'))}</b> min.`);el.innerHTML=out.map(x=>`<div class="insight">${x}<div class="small">Association only—not proof of cause.</div></div>`).join('')}
function history(){let h=document.getElementById('history');if(!entries.length){h.innerHTML='<p class="empty">No entries yet.</p>';return}h.innerHTML=entries.map((e,i)=>`<div class="history-item"><b>${e.date}</b><div class="scores">Calm ${e.calm} · Restless ${e.restless} · Anxiety ${e.anxiety} · Focus ${e.focus} · Study ${e.study}m · Gym ${e.gym?'Yes':'No'}</div>${e.note?`<div>${e.note}</div>`:''}</div>`).join('')}
function chart(){let c=document.getElementById('chart'),ctx=c.getContext('2d'),w=c.width=c.clientWidth*2,h=c.height=360;ctx.scale(2,2);w/=2;h/=2;ctx.clearRect(0,0,w,h);let a=[...entries].sort((x,y)=>x.date.localeCompare(y.date)).slice(-14);if(a.length<2)return;ctx.beginPath();a.forEach((e,i)=>{let x=12+i*(w-24)/(a.length-1),y=10+(10-e.calm)*(h-25)/10;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.font='12px sans-serif';ctx.fillText('Calmness (last 14 entries)',12,20)}
function render(){renderForm();insights();history();chart()}document.getElementById('save').onclick=save;document.getElementById('export').onclick=()=>{let blob=new Blob([JSON.stringify(entries,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='state-backup.json';a.click()};document.getElementById('clear').onclick=()=>{if(confirm('Delete all entries?')){entries=[];localStorage.removeItem(KEY);render()}};render();